### ISSUE TITLE
Graphics Context Kivy breaks when super is used

### ISSUE THREAD

**Issue by andnovar** [andnovar/kivy#49]

**Comment by andnovar** [comment]
Traceback (most recent call last):
   File "test_plt.py", line 58, in <module>
     figure, ax = plt.subplots()
   File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 1078, in subplots
     fig = figure(*_fig_kw)
   File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 435, in figure
     *_kwargs)
   File "/home/andnovar/Documents/libraries/kivy_fork/kivy/kivy/ext/mpl/backend_kivy.py", line 628, in new_figure_manager
     return new_figure_manager_given_figure(num, thisFig)
   File "/home/andnovar/Documents/libraries/kivy_fork/kivy/kivy/ext/mpl/backend_kivy.py", line 636, in new_figure_manager_given_figure
     canvas.draw()
   File "/home/andnovar/Documents/libraries/kivy_fork/kivy/kivy/ext/mpl/backend_kivy.py", line 673, in draw
     self.figure.draw(renderer)
   File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/artist.py", line 59, in draw_wrapper
     draw(artist, renderer, _args, *_kwargs)
   File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/figure.py", line 1023, in draw
     self.patch.draw(renderer)
   File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/artist.py", line 59, in draw_wrapper
     draw(artist, renderer, _args, *_kwargs)
   File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/patches.py", line 441, in draw
     gc = renderer.new_gc()
   File "/home/andnovar/Documents/libraries/kivy_fork/kivy/kivy/ext/mpl/backend_kivy.py", line 443, in new_gc
     return GraphicsContextKivy(self.widget)
   File "/home/andnovar/Documents/libraries/kivy_fork/kivy/kivy/ext/mpl/backend_kivy.py", line 534, in **init**
     super(GraphicsContextKivy, self).**init**()
 TypeError: must be type, not classobj

**Comment by andnovar** [comment]
http://stackoverflow.com/questions/9698614/super-raises-typeerror-must-be-type-not-classobj-for-new-style-class

It will be fixed in matplotlib 1.5.1 I checked the class.
